# Generated by Django 4.2.1 on 2023-09-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questionsolutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicExplaination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(max_length=3000)),
                ('explaintaion', models.JSONField()),
            ],
        ),
    ]
