# Generated by Django 4.2.1 on 2023-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_topicexplaination'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicexplaination',
            name='for_class',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='topicexplaination',
            name='language',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
