# Generated by Django 4.2.1 on 2023-09-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('session', '0001_initial'),
        ('classes', '__first__'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classsection'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_no',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'registration_no')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=40)),
                ('class_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classsection')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('school', 'registration_no', 'session')},
            },
        ),
    ]
